// ...existing code...
const translations = {
  pl: {
    title: "Nina PLUs PAint",
    new: "Nowe",
    open: "Otwórz",
    save: "Zapisz PNG",
    undo: "↶ Cofnij",
    redo: "↷ Ponów",
    clear: "Wyczyść",
    tool_brush: "Pędzel",
    tool_eraser: "Gumka",
    tool_line: "Linia",
    tool_rect: "Prostokąt",
    tool_circle: "Okrąg",
    tool_fill: "Wypełnij",
    tool_text: "Tekst",
    tool_pipette: "Pipeta",
    tool_spray: "Spray",
    tool_rainbow: "Tęcza",
    tool_randomShape: "Losowy Kształt",
    tool_shuffle: "Glitch",
    // modloader
    modloader_title: "Catalog for Mods v1",
    modloader_url_label: "URL do moda (.js)",
    modloader_load_url: "Załaduj z URL",
    modloader_choose_file_label: "Lub wybierz plik .js z dysku",
    modloader_choose_file_btn: "Wybierz plik (Explorer)",
    modloader_status_loaded: "Mod załadowany: ",
    modloader_status_error: "Błąd ładowania moda: ",
    modloader_loaded_mods: "Załadowane mody",
    modloader_remove_btn: "Usuń",
    modloader_no_file_selected: "Nie wybrano pliku",
    modloader_invalid_url: "Podaj poprawny URL do pliku .js",
    // Nina random size
    nina_title: "Nina (losowy rozmiar)",
    nina_loaded: "nina-mod załadowany — kliknij canvas by wstawić \"Nina\"",
    // Hue / Drop Nori
    hue_title: "Hue Stamp",
    hue_load_btn: "Wczytaj",
    hue_random_label: "losowy odcień",
    hue_hue_val: "°",
    hue_size_label: "Rozmiar",
    hue_rotation_label: "losowy obrót",
    hue_close: "Zamknij",
    hue_desc: "Wczytaj obraz, kliknij canvas by wstemplować z przesunięciem odcienia.",
    // Surreal
    surreal_title: "Surreal Stamp",
    surreal_generate: "Generuj Surreal",
    surreal_at_cursor: "W miejscu kursora",
    surreal_close: "Zamknij",
    surreal_desc: "Generuje warstwowy, proceduralny obraz",
    // Paint V2 badge
    paint_v2_loaded: "Paint V2: oznaczono V2",
    // Line Trace
    line_trace_title: "Line Trace",
    line_trace_load: "Wczytaj",
    line_trace_threshold: "Threshold",
    line_trace_line_color: "Kolor linii",
    line_trace_trace: "Trace & Stamp (środek)",
    line_trace_stamp_cursor: "Wstaw w kursora",
    line_trace_close: "Zamknij",
    line_trace_desc: "Wczytaj obraz, ustaw threshold i wstaw cienkie linie.",
    // Image Texture Brush
    itb_title: "Image Texture Brush",
    itb_load_file: "Wczytaj plik",
    itb_size: "Rozmiar",
    itb_spacing: "Spacing",
    itb_opacity: "Przezroczystość",
    itb_blend: "Blend",
    itb_tile: "Tile",
    itb_rot_jitter: "Rot jitter",
    itb_scale_jitter: "Scale jitter",
    itb_brush: "Brush",
    itb_stamp: "Stamp",
    itb_preview: "Preview",
    itb_close: "Zamknij",
    itb_desc: "Wczytaj teksturę i maluj nią po canvasie.",
    // Robux joke
    robux_title: "Robux (żart)",
    robux_input_placeholder: "Wpisz nick (żart)",
    robux_add: "Dodaj 100R",
    robux_close: "Zamknij",
    robux_toast: "100R zostało dodane do konta {nick}",
    // Line Rebuild
    lr_title: "Line Rebuild",
    lr_load: "Wczytaj",
    lr_threshold: "Threshold",
    lr_minlen: "Min stroke len",
    lr_smooth: "Smooth iters",
    lr_lw: "Line width",
    lr_rebuild: "Rebuild & Stamp (środek)",
    lr_stamp_cursor: "Wstaw w kursora",
    lr_close: "Zamknij",
    lr_desc: "Tworzy dłuższe, połączone i wygładzone kreski z krawędzi obrazu."
  },
  en: {
    title: "Nina PLUs PAint",
    new: "New",
    open: "Open",
    save: "Save PNG",
    undo: "Undo ↶",
    redo: "Redo ↷",
    clear: "Clear",
    tool_brush: "Brush",
    tool_eraser: "Eraser",
    tool_line: "Line",
    tool_rect: "Rectangle",
    tool_circle: "Circle",
    tool_fill: "Fill",
    tool_text: "Text",
    tool_pipette: "Eyedropper",
    tool_spray: "Spray",
    tool_rainbow: "Rainbow",
    tool_randomShape: "Random Shape",
    tool_shuffle: "Glitch",
    // modloader
    modloader_title: "Catalog for Mods v1",
    modloader_url_label: "Mod URL (.js)",
    modloader_load_url: "Load from URL",
    modloader_choose_file_label: "Or choose a .js file from disk",
    modloader_choose_file_btn: "Choose file (Explorer)",
    modloader_status_loaded: "Mod loaded: ",
    modloader_status_error: "Error loading mod: ",
    modloader_loaded_mods: "Loaded mods",
    modloader_remove_btn: "Remove",
    modloader_no_file_selected: "No file selected",
    modloader_invalid_url: "Provide a valid .js file URL",
    // Nina random size
    nina_title: "Nina (random size)",
    nina_loaded: "nina-mod loaded — click canvas to spawn \"Nina\"",
    // Hue / Drop Nori
    hue_title: "Hue Stamp",
    hue_load_btn: "Load",
    hue_random_label: "random hue",
    hue_hue_val: "°",
    hue_size_label: "Size",
    hue_rotation_label: "random rotation",
    hue_close: "Close",
    hue_desc: "Load image, click canvas to stamp with hue shift.",
    // Surreal
    surreal_title: "Surreal Stamp",
    surreal_generate: "Generate Surreal",
    surreal_at_cursor: "At Cursor",
    surreal_close: "Close",
    surreal_desc: "Generates layered procedural imagery",
    // Paint V2 badge
    paint_v2_loaded: "Paint V2: badge applied",
    // Line Trace
    line_trace_title: "Line Trace",
    line_trace_load: "Load",
    line_trace_threshold: "Threshold",
    line_trace_line_color: "Line color",
    line_trace_trace: "Trace & Stamp (center)",
    line_trace_stamp_cursor: "Stamp at Cursor",
    line_trace_close: "Close",
    line_trace_desc: "Load image, adjust threshold, then stamp thin-line drawing.",
    // Image Texture Brush
    itb_title: "Image Texture Brush",
    itb_load_file: "Load file",
    itb_size: "Size",
    itb_spacing: "Spacing",
    itb_opacity: "Opacity",
    itb_blend: "Blend",
    itb_tile: "Tile",
    itb_rot_jitter: "Rot jitter",
    itb_scale_jitter: "Scale jitter",
    itb_brush: "Brush",
    itb_stamp: "Stamp",
    itb_preview: "Preview",
    itb_close: "Close",
    itb_desc: "Load a texture and paint with it on the canvas.",
    // Robux joke
    robux_title: "Robux (joke)",
    robux_input_placeholder: "Enter nick (joke)",
    robux_add: "Add 100R",
    robux_close: "Close",
    robux_toast: "100R added to account {nick}",
    // Line Rebuild
    lr_title: "Line Rebuild",
    lr_load: "Load",
    lr_threshold: "Threshold",
    lr_minlen: "Min stroke len",
    lr_smooth: "Smooth iters",
    lr_lw: "Line width",
    lr_rebuild: "Rebuild & Stamp (center)",
    lr_stamp_cursor: "Stamp at Cursor",
    lr_close: "Close",
    lr_desc: "Creates longer connected smooth strokes from image edges."
  },
  ar: {
    title: "نينا بلس بينت",
    new: "جديد",
    open: "فتح",
    save: "حفظ PNG",
    undo: "↶ تراجع",
    redo: "↷ إعادة",
    clear: "مسح",
    tool_brush: "فرشاة",
    tool_eraser: "ممحاة",
    tool_line: "خط",
    tool_rect: "مستطيل",
    tool_circle: "دائرة",
    tool_fill: "تعبئة",
    tool_text: "نص",
    tool_pipette: "قطارة",
    tool_spray: "رش",
    tool_rainbow: "قوس قزح",
    tool_randomShape: "شكل عشوائي",
    tool_shuffle: "خلل",
    // modloader
    modloader_title: "كتالوج الإضافات v1",
    modloader_url_label: "رابط الإضافة (.js)",
    modloader_load_url: "تحميل من الرابط",
    modloader_choose_file_label: "أو اختر ملف .js من القرص",
    modloader_choose_file_btn: "اختر ملف (المستعرض)",
    modloader_status_loaded: "تم تحميل الإضافة: ",
    modloader_status_error: "خطأ في تحميل الإضافة: ",
    modloader_loaded_mods: "الإضافات المحملة",
    modloader_remove_btn: "إزالة",
    modloader_no_file_selected: "لم يتم اختيار ملف",
    modloader_invalid_url: "أدخل رابط ملف .js صالح",
    // Nina random size
    nina_title: "نينا (حجم عشوائي)",
    nina_loaded: "تم تحميل nina-mod — انقر على اللوحة لعرض \"Nina\"",
    // Hue / Drop Nori
    hue_title: "ختم اللون",
    hue_load_btn: "تحميل",
    hue_random_label: "لون عشوائي",
    hue_hue_val: "°",
    hue_size_label: "الحجم",
    hue_rotation_label: "دوران عشوائي",
    hue_close: "إغلاق",
    hue_desc: "حمّل صورة، ثم انقر على اللوحة للختم مع تغيير اللون.",
    // Surreal
    surreal_title: "ختم سريالي",
    surreal_generate: "توليد سريالي",
    surreal_at_cursor: "عند المؤشر",
    surreal_close: "إغلاق",
    surreal_desc: "ينشئ صورة إجرائية طبقية",
    // Paint V2 badge
    paint_v2_loaded: "Paint V2: تم إضافة الشارة",
    // Line Trace
    line_trace_title: "تتبع الخط",
    line_trace_load: "تحميل",
    line_trace_threshold: "العتبة",
    line_trace_line_color: "لون الخط",
    line_trace_trace: "تتبع وختم (الوسط)",
    line_trace_stamp_cursor: "الختم عند المؤشر",
    line_trace_close: "إغلاق",
    line_trace_desc: "حمّل صورة، اضبط العتبة، ثم ختم رسم خطوط رفيعة.",
    // Image Texture Brush
    itb_title: "فرشاة نسيج الصورة",
    itb_load_file: "تحميل ملف",
    itb_size: "الحجم",
    itb_spacing: "المسافة",
    itb_opacity: "الشفافية",
    itb_blend: "الدمج",
    itb_tile: "تكرار",
    itb_rot_jitter: "اهتزاز دوران",
    itb_scale_jitter: "اهتزاز مقياس",
    itb_brush: "فرشاة",
    itb_stamp: "ختم",
    itb_preview: "معاينة",
    itb_close: "إغلاق",
    itb_desc: "حمّل نسيجًا و ارسم به على اللوحة.",
    // Robux joke
    robux_title: "روبوكس (مزحة)",
    robux_input_placeholder: "أدخل اسم المستخدم (مزحة)",
    robux_add: "أضف 100R",
    robux_close: "إغلاق",
    robux_toast: "تمت إضافة 100R إلى حساب {nick}",
    // Line Rebuild
    lr_title: "إعادة بناء الخط",
    lr_load: "تحميل",
    lr_threshold: "العتبة",
    lr_minlen: "الحد الأدنى لطول الضربة",
    lr_smooth: "تنعيم التكرارات",
    lr_lw: "عرض الخط",
    lr_rebuild: "إعادة بناء وختم (الوسط)",
    lr_stamp_cursor: "الختم عند المؤشر",
    lr_close: "إغلاق",
    lr_desc: "ينشئ ضربات أطول ومتصلة ومُنعَمة من حواف الصورة."
  },
  ja: {
    title: "Nina PLUs PAint",
    new: "新規",
    open: "開く",
    save: "PNG保存",
    undo: "↶ 元に戻す",
    redo: "↷ やり直す",
    clear: "クリア",
    tool_brush: "ブラシ",
    tool_eraser: "消しゴム",
    tool_line: "線",
    tool_rect: "四角形",
    tool_circle: "円",
    tool_fill: "塗りつぶし",
    tool_text: "テキスト",
    tool_pipette: "スポイト",
    tool_spray: "スプレー",
    tool_rainbow: "虹",
    tool_randomShape: "ランダム形",
    tool_shuffle: "グリッチ",
    // modloader
    modloader_title: "Mod カタログ v1",
    modloader_url_label: "Mod の URL (.js)",
    modloader_load_url: "URL から読み込む",
    modloader_choose_file_label: "またはディスクから .js ファイルを選択",
    modloader_choose_file_btn: "ファイルを選択 (エクスプローラー)",
    modloader_status_loaded: "モッドを読み込みました: ",
    modloader_status_error: "モッドの読み込みエラー: ",
    modloader_loaded_mods: "読み込まれたモッド",
    modloader_remove_btn: "削除",
    modloader_no_file_selected: "ファイルが選択されていません",
    modloader_invalid_url: ".js ファイルの有効な URL を入力してください",
    // Nina random size
    nina_title: "Nina（ランダムサイズ）",
    nina_loaded: "nina-mod 読み込み完了 — キャンバスをクリックして「Nina」を生成",
    // Hue / Drop Nori
    hue_title: "色相スタンプ",
    hue_load_btn: "読み込む",
    hue_random_label: "ランダム色相",
    hue_hue_val: "°",
    hue_size_label: "サイズ",
    hue_rotation_label: "ランダム回転",
    hue_close: "閉じる",
    hue_desc: "画像を読み込み、キャンバスをクリックして色相をずらしてスタンプします。",
    // Surreal
    surreal_title: "超現実スタンプ",
    surreal_generate: "生成",
    surreal_at_cursor: "カーソル位置",
    surreal_close: "閉じる",
    surreal_desc: "レイヤー化された手続き的な画像を生成します",
    // Paint V2 badge
    paint_v2_loaded: "Paint V2: バッジを追加しました",
    // Line Trace
    line_trace_title: "ライントレース",
    line_trace_load: "読み込む",
    line_trace_threshold: "閾値",
    line_trace_line_color: "線の色",
    line_trace_trace: "トレース & スタンプ（中央）",
    line_trace_stamp_cursor: "カーソルにスタンプ",
    line_trace_close: "閉じる",
    line_trace_desc: "画像を読み込み、閾値を調整して細い線をスタンプします。",
    // Image Texture Brush
    itb_title: "イメージテクスチャーブラシ",
    itb_load_file: "ファイルを読み込む",
    itb_size: "サイズ",
    itb_spacing: "間隔",
    itb_opacity: "不透明度",
    itb_blend: "合成",
    itb_tile: "タイル",
    itb_rot_jitter: "回転ジッター",
    itb_scale_jitter: "スケールジッター",
    itb_brush: "ブラシ",
    itb_stamp: "スタンプ",
    itb_preview: "プレビュー",
    itb_close: "閉じる",
    itb_desc: "テクスチャを読み込み、それでキャンバスに描画します。",
    // Robux joke
    robux_title: "ロブックス（ジョーク）",
    robux_input_placeholder: "ニックネームを入力（ジョーク）",
    robux_add: "100R を追加",
    robux_close: "閉じる",
    robux_toast: "{nick} のアカウントに 100R が追加されました",
    // Line Rebuild
    lr_title: "ラインリビルド",
    lr_load: "読み込む",
    lr_threshold: "閾値",
    lr_minlen: "最小ストローク長",
    lr_smooth: "スムーズ反復",
    lr_lw: "線の太さ",
    lr_rebuild: "リビルド & スタンプ（中央）",
    lr_stamp_cursor: "カーソルにスタンプ",
    lr_close: "閉じる",
    lr_desc: "画像のエッジから長く連結された滑らかなストロークを作成します。"
  }
};
// Funkcja zmiany języka
function setLanguage(lang){
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if(translations[lang] && translations[lang][key]){
      el.textContent = translations[lang][key];
    }
  });

  // dodatkowe pola modloadera (jeśli chcesz przy dynamicznej zmianie tekstów)
  if(translations[lang]) {
    const t = translations[lang];
    const titleEl = document.querySelector('.mods-panel h3');
    if(titleEl && t.modloader_title) titleEl.textContent = t.modloader_title;
    const urlLabel = document.querySelector('.modloader label');
    if(urlLabel && t.modloader_url_label) urlLabel.textContent = t.modloader_url_label;
    const loadBtn = document.getElementById('load-mod-btn');
    if(loadBtn && t.modloader_load_url) loadBtn.textContent = t.modloader_load_url;
    const chooseLabel = document.querySelector('.modloader > div label');
    if(chooseLabel && t.modloader_choose_file_label) chooseLabel.textContent = t.modloader_choose_file_label;
    const chooseBtn = document.getElementById('load-mod-file-btn');
    if(chooseBtn && t.modloader_choose_file_btn) chooseBtn.textContent = t.modloader_choose_file_btn;
    const loadedHeader = document.querySelector('.modloader h4');
    if(loadedHeader && t.modloader_loaded_mods) loadedHeader.textContent = t.modloader_loaded_mods;
  }
}